name: 'Deploy to Transformations'
description: 'Deploy a set of transformations to Transformations from yaml manifests'
inputs:
  api-key:
    description: 'API key for authenticating with Transformations'
    required: false
  token-url:
    description: 'Token url to use for fetching OIDC tokens'
    required: false
  token-project:
    description: 'CDF project name (only required when using OIDC credentials)'
    required: false
  token-scopes:
    description: 'List of OIDC scopes (comma separated)'
    required: false
  token-client-id:
    description: 'OAuth2 client ID'
    required: false
  token-client-secret:
    description: 'OAuth2 client secret'
    required: false
  cluster:
    description: 'CDF Cluster'
    required: false
    default: 'europe-west1-1'
  path:
    description: >-
      The path to a directory containing transformation manifests.
      This is relative to $GITHUB_WORKSPACE,
      which will be the root of the repository when using actions/checkout with default settings.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TRANSFORMATIONS_API_KEY: ${{ inputs.api-key }}
    TRANSFORMATIONS_TOKEN_URL: ${{ inputs.token-url }}
    TRANSFORMATIONS_PROJECT: ${{ inputs.token-project }}
    TRANSFORMATIONS_CLIENT_ID: ${{ inputs.token-client-id }}
    TRANSFORMATIONS_CLIENT_SECRET: ${{ inputs.token-client-secret }}
    TRANSFORMATIONS_SCOPES: ${{ inputs.token-scopes }}
    TRANSFORMATIONS_CLUSTER: "${{ inputs.cluster }}"
  args: ["deploy", "--path=${{ inputs.path }}" ]