# gcr.io/distroless/python3-debian11 (runtime env is using 3.9 and that's imporatant for native dependencies)
FROM python:3.14-slim AS builder

WORKDIR /

ENV PYTHONUNBUFFERED=1

# Poetry setup
RUN pip3 install poetry==1.8.3
RUN poetry config virtualenvs.create false

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry config virtualenvs.create false
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes
RUN pip3 install --target=/app -r requirements.txt --no-deps

# Keep the same folder structure for imports
COPY cognite/transformations_cli/ /app/cognite/transformations_cli/

# Distroless does not work with Azure pipelines
FROM python:3.13-bullseye
COPY --from=builder /app /app
ENV PYTHONPATH /app

